name: Solar System workflow
on:
    workflow_dispatch: 
    push:
        branches: 
            - main
            - 'feature/*'
jobs:
    unit-testing:
        name: Unit testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              run: actions/checkout@v4

            - name: Setup NodeJs version-18
              run: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install
              
            - name: Unit testing
              run: npm test